name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Set up Python
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x' # Cambia '3.x' por la versión de Python que necesites

      # Install dependencies (si tienes un archivo requirements.txt o pyproject.toml)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

      # Ejecutar main.py
      - name: Run main.py
        run: python main.py
